CREATE DATABASE TOTNGHIEP;
USE TOTNGHIEP;
CREATE TABLE TRUONG (
    MaTruong VARCHAR(10) PRIMARY KEY,
    TenTruong VARCHAR(100),
    DiaChi VARCHAR(200),
    SoDT VARCHAR(15)
);

CREATE TABLE NGANH (
    MaNganh VARCHAR(10) PRIMARY KEY,
    TenNganh VARCHAR(100),
    LoaiNganh VARCHAR(50)
);

CREATE TABLE SINHVIEN (
    SoCMND VARCHAR(12) PRIMARY KEY,
    HoTen VARCHAR(100),
    Email VARCHAR(100),
    SoDT VARCHAR(15),
    DiaChi VARCHAR(200)
);

CREATE TABLE TOT_NGHIEP (
    SoCMND VARCHAR(12),
    MaTruong VARCHAR(10),
    MaNganh VARCHAR(10),
    HeTN VARCHAR(50),
    NgayTN DATE,
    LoaiTN VARCHAR(50),
    PRIMARY KEY (SoCMND, MaTruong, MaNganh),
    FOREIGN KEY (SoCMND) REFERENCES SINHVIEN(SoCMND),
    FOREIGN KEY (MaTruong) REFERENCES TRUONG(MaTruong),
    FOREIGN KEY (MaNganh) REFERENCES NGANH(MaNganh)
);

CREATE TABLE CONG_VIEC (
    SoCMND VARCHAR(12),
    NgayVaoCongTy DATE,
    MaNganh VARCHAR(10),
    TenCongViec VARCHAR(100),
    TenCongTy VARCHAR(100),
    DiaChiCongTy VARCHAR(200),
    ThoiGianLamViec INT,
    PRIMARY KEY (SoCMND, NgayVaoCongTy),
    FOREIGN KEY (SoCMND) REFERENCES SINHVIEN(SoCMND),
    FOREIGN KEY (MaNganh) REFERENCES NGANH(MaNganh)
);
